Remove server and client options
I wasn't quite satisfied with the implementation.
Will have to rethink the concept and implement it
again, a bit smarter.

Signed-off-by: Haris Gušić <harisgusic.dev@gmail.com>

diff --git a/tuterm b/tuterm
--- a/tuterm
+++ b/tuterm
@@ -4,8 +4,6 @@ __VERSION='0.0.0'
 [ -z "$__TUTERM_PREFIX" ] &&\
     __TUTERM_PREFIX='/usr/local'
 
-# TODO Make the recent changes work in client-server mode
-
 # ┏━━━━━━━━━━━━━━━━━━┓
 # ┃ Helper functions ┃
 # ┗━━━━━━━━━━━━━━━━━━┛
@@ -69,42 +67,32 @@ __abspath() {
 
 cmdline() {
     prompt
-    if ! option 'client'; then
-        stty -echo
-        option 'fast' || sleep $DELAY_PROMPT  # Wait a small delay after prompt
-        ! mode 'demo' && color cmdline
-        __print_out "$*"; color 0 # Type out the command line
-        echo
-        stty echo
+    stty -echo
+    option 'fast' || sleep $DELAY_PROMPT    # Wait a small delay after prompt
+    if ! mode 'demo'; then
+        color cmdline
     fi
+    __print_out "$*"; color 0; echo         # Type out the command line
+    stty echo
     if mode 'tutorial'; then
+        prompt
         __USER_INPUT=''
-        if option 'server'; then                        # --server
-            read __discard < "/tmp/tuterm_client_$$"    # Wait for continue signal
-        else                                            # not --server
-            if ! option 'client'; then prompt; fi
-            read __USER_INPUT                           # Read user input
-            if [ "$__USER_INPUT" != "$*" ]; then        # Oops, wrong input
-                color warning >&2
-                echo -e "Wrong command, try again" >&2
-                color 0 >&2
-                __OPT_FAST='true' cmdline "$@"
-                return
-            fi
-            # Send continue signal to server
-            if option 'client'; then
-                echo CONTINUE > "/tmp/tuterm_client_$__ARG_PID"
-            fi
+        read __USER_INPUT                           # Read user input
+        if [ "$__USER_INPUT" != "$*" ]; then        # Oops, wrong input
+            color warning >&2
+            echo -e "Wrong command, try again" >&2
+            color 0 >&2
+            __OPT_FAST='true' cmdline "$@"
+            return
         fi
     fi
     # Run the command that was entered into the command line
-    if ! option 'server'; then "$@"; fi
+    "$@"
 }
 readonly -f cmdline; alias c=cmdline
 
 # Message that works in both tutorial and demo mode
 Message() {
-    if option 'client'; then return 0; fi
     color message
     echo "$@"
     color 0
@@ -138,17 +126,15 @@ mode() {
 readonly -f mode
 
 fake_home() {
-    if ! option 'client'; then
-        local random="$(shuf -erz -n20 {A..Z} {a..z} {0..9} | tr -d '\0')"
-        local dest="/tmp/tuterm/HOME_$random"
-        if ! mkdir -p "$dest"; then
-            echo -e 'tuterm: error: could not create fake home!\nAborting.' >&2
-            exit 1
-        fi
-        cd "$dest"
-        readonly __FAKE_HOME="$dest"
-        HOME="$dest"
+    local random="$(shuf -erz -n20 {A..Z} {a..z} {0..9} | tr -d '\0')"
+    local dest="/tmp/tuterm/HOME_$random"
+    if ! mkdir -p "$dest"; then
+        echo -e 'tuterm: error: could not create fake home!\nAborting.' >&2
+        exit 1
     fi
+    cd "$dest"
+    readonly __FAKE_HOME="$dest"
+    HOME="$dest"
 }
 readonly -f fake_home
 
@@ -187,8 +173,8 @@ shopt -s expand_aliases
 # ┃ PARSE OPTIONS ┃
 # ┗━━━━━━━━━━━━━━━┛
 
-__arguments=$(getopt --options 'hvpfsclm:'\
-                        --long 'help,version,path,fast,server,client,list,mode:'\
+__arguments=$(getopt --options 'hvpflm:'\
+                        --long 'help,version,path,fast,list,mode:'\
                         --name 'tuterm'\
                             -- "$@")
 [ $? != 0 ] && exit
@@ -202,10 +188,7 @@ __usage() {
     echo -e '  -v, --version        \tprint tuterm version'
     echo -e '  -m, --mode MODE      \tselect MODE: tutorial (default) or demo'
     echo -e '  -f, --fast           \tdo not type characters in real time'
-    echo -e '  -s, --server         \tonly show instructions in this shell'
-    echo -e '  -c, --client         \tprovide user interaction for tutorial'
     echo -e '  -l, --list           \tlist installed tuterm scripts'
-    # echo -e '  -L, --list-running   \tlist running tuterm servers'
 }
 
 # Transform options generated by getopt into a proper array
@@ -221,8 +204,6 @@ for i in "${!__arguments[@]}"; do
 done
 
 __OPT_FAST=''
-__OPT_SERVER=''
-__OPT_CLIENT=''
 __OPT_MODE='tutorial'
 __ARG_FILE=''
 
@@ -239,12 +220,6 @@ do
             exit ;;
         '-f'|'--fast')
             readonly __OPT_FAST='true'
-            continue ;;
-        '-s'|'--server')
-            readonly __OPT_SERVER='true'
-            continue ;;
-        '-c'|'--client')
-            readonly __OPT_CLIENT='true'
             continue ;;
         '-m'|'--mode')
             readonly __OPT_MODE="${__options[((i+1))]}"
@@ -280,32 +255,12 @@ if [[ "$__ARG_FILE" != */* ]]; then
 fi
 __ARG_FILE="$(__abspath "$__ARG_FILE")"
 
-if ! option 'client' && [ ! -f "$__ARG_FILE" ]; then
+if [ ! -f "$__ARG_FILE" ]; then
     echo 'tuterm: error: script file does not exist' >&2
     exit 1
 fi
 
-# Create a backup of the tutorial script in shm
-if mode 'tutorial' && option 'server'; then             # --tutorial --server
-    cat "$__ARG_FILE" > "/dev/shm/tuterm_server_$$"
-fi
-
-if mode 'tutorial' && option 'client'; then             # --tutorial --client
-    # If no server pid is specified, try to detect it (TODO multiple servers?)
-    [ -z "$__ARG_PID" ] &&
-        __ARG_PID="$(ls /tmp/tuterm_server_* 2>/dev/null | head -1)"
-    __ARG_PID="${__ARG_PID##/tmp/tuterm_server_}"
-    # The client does not take a file argument, it will use the file
-    # /dev/shm/tuterm_server_* created by the server
-    __ARG_FILE="/dev/shm/tuterm_server_$__ARG_PID"
-    # Exit if the pid is invalid
-    if ! kill -0 "$__ARG_PID" 2>/dev/null || [ ! -p "/tmp/tuterm_server_$__ARG_PID" ]
-    then
-        echo 'tuterm: invalid server PID' >&2; exit 1
-    fi
-else
-    [ -z "$__ARG_FILE" ] && { echo 'tuterm: no file specified' >&2; exit 1; }
-fi
+[ -z "$__ARG_FILE" ] && { echo 'tuterm: no file specified' >&2; exit 1; }
 
 # Make argument variables read-only
 readonly __ARG_FILE __ARG_PID
@@ -314,26 +269,15 @@ readonly __ARG_FILE __ARG_PID
 # ┃ RUN SCRIPT ┃
 # ┗━━━━━━━━━━━━┛
 
-if mode 'demo' || option 'server'; then
+if mode 'demo'; then
     # Disable user input in the terminal
     # TODO actually, this just makes it invisible. stty -cread doesn't work,
     # must look into that
     stty -echo
 fi
 
-# --tutorial --server
-mode 'tutorial' && option 'server' && {
-    # Create a FIFO to communicate with client shell
-    mkfifo "/tmp/tuterm_server_$$" "/tmp/tuterm_client_$$"
-}
-
 # Exit cleanup
 __on_exit() {
-    # Remove inter-process files
-    mode 'tutorial' && option 'server' && {
-        rm -f "/dev/shm/tuterm_server_$$"
-        rm -f "/tmp/tuterm_server_$$" "/tmp/tuterm_client_$$"
-    }
     # Remove fake home if it was created
     [ -n "$__FAKE_HOME" ] && rm -rf "$__FAKE_HOME"
 }
@@ -352,8 +296,6 @@ readonly TUTERM_SCRIPT="$__ARG_FILE"
 [ -z "$DELAY_PROMPT" ]  && DELAY_PROMPT="$DELAY"
 [ -z "$TUTERM_NAME" ]   && TUTERM_NAME="$(basename "$TUTERM_SCRIPT")"
 
-# TODO remove this
-# [ "$(type -t setup)" = 'function'] && setup     # Perform any additional setup for the tutorial
 clear
 run
 
