Sort out command line parsing
Signed-off-by: Haris Gušić <harisgusic.dev@gmail.com>

diff --git a/tuterm b/tuterm
--- a/tuterm
+++ b/tuterm
@@ -179,10 +179,13 @@ shopt -s expand_aliases
 # ┃ PARSE OPTIONS ┃
 # ┗━━━━━━━━━━━━━━━┛
 
-options=$(getopt -o 'hvpfsclm:' --long 'help,version,path,fast,server,client,list,mode:' -n 'tuterm' -- "$@")
+__arguments=$(getopt --options 'hvpfsclm:'\
+                        --long 'help,version,path,fast,server,client,list,mode:'\
+                        --name 'tuterm'\
+                            -- "$@")
 [ $? != 0 ] && exit
 
-usage() {
+__usage() {
     echo -e 'usage: tuterm [-h] [-f] [COMMAND] FILE'
     echo -e '\npositional arguments:'
     echo -e '  FILE                 \tsource file for the tutorial'
@@ -197,18 +200,31 @@ usage() {
     # echo -e '  -L, --list-running   \tlist running tuterm servers'
 }
 
+# Transform options generated by getopt into a proper array
+eval __arguments=(${__arguments[@]})
+# Split array __arguments into two arrays: __options (arguments before '--')
+# and __positional (arguments after '--')
+for i in "${!__arguments[@]}"; do
+    if [ "${__arguments[$i]}" = '--' ]; then
+        __options=("${__arguments[@]::$i}")
+        __positional=("${__arguments[@]:((i+1))}")
+        break
+    fi
+done
+
 __OPT_FAST=''
 __OPT_SERVER=''
 __OPT_CLIENT=''
 __OPT_MODE='tutorial'
 __ARG_FILE=''
 
-for opt in $options
+# Parse options
+# ━━━━━━━━━━━━━
+for i in "${!__options[@]}"
 do
-    [ "$1" = "$(eval echo $opt)" ] && shift || continue
-    case "$opt" in
+    case "${__options[$i]}" in
         '-h'|'--help')
-            usage
+            __usage
             exit ;;
         '-v'|'--version')
             echo "tuterm version $__VERSION"
@@ -223,23 +239,25 @@ do
             readonly __OPT_CLIENT='true'
             continue ;;
         '-m'|'--mode')
-            readonly __OPT_MODE="$1"
-            echo 'hi'
-            shift
+            readonly __OPT_MODE="${__options[((i+1))]}"
             continue ;;
         '-l'|'--list')
-            command ls -1 /usr/share/tuterm/scripts
+            ls -1 /usr/share/tuterm/scripts
             exit ;;
-        *)
-            # There are multiple file arguments -- error
-            if [ -n "$__ARG_FILE" ]; then
-                echo 'tuterm: only one file argument is allowed' >&2
-                exit 1
-            fi
-            __ARG_FILE="$(eval echo $opt)"
-            ;;
     esac
 done
+
+# Parse positional arguments
+# ━━━━━━━━━━━━━━━━━━━━━━━━━━
+if [ "${#__positional[@]}" = 1 ]; then                  # One positional argument
+    __ARG_FILE="$__positional"
+elif [ "${#__positional[@]}" = 0 ]; then                # No positional arguments
+    echo 'tuterm: error: no script file specified' >&2
+    exit 1
+else                                                    # Multiple arguments
+    echo 'tuterm: error: only one file argument is allowed' >&2
+    exit 1
+fi
 
 # ┏━━━━━━━━━━━━━━━━━━━━━┓
 # ┃ ARGUMENT PROCESSING ┃
@@ -253,11 +271,6 @@ if [[ "$__ARG_FILE" != */* ]]; then
     [ -f "$__file" ]  && __ARG_FILE="$__file"
 fi
 __ARG_FILE="$(abspath "$__ARG_FILE")"
-
-if [ -z "$__ARG_FILE" ]; then
-    echo 'tuterm: error: no script file specified' >&2
-    exit 1
-fi
 
 if ! option 'client' && [ ! -f "$__ARG_FILE" ]; then
     echo 'tuterm: error: script file does not exist' >&2
@@ -327,7 +340,7 @@ readonly TUTORIAL_FILE="$__ARG_FILE"
 [ -z "$DELAY_PROMPT" ]  && DELAY_PROMPT="$DELAY"
 
 setup                           # Perform any additional setup for the tutorial
-# clear
+clear
 run
 
 # vim: filetype=sh foldmethod=syntax
